---
blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: "https://github.com/benbenbang/raycast-clip/discussions/new/choose"
    about: "Ask a question about Short URL or anything that doesn't fit into a bug report or feature request."
